Importing the libraries


In [67]:
import numpy as np
import pandas as pd


IMPORTING THE DATASET


In [68]:
Df = pd.read_csv("BABYFISH.csv")
Df.head()


Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [69]:
X = Df.iloc[:, 1:]
y = Df['Species']


In [70]:
print(X, y)


     Weight  Length1  Length2  Length3   Height   Width
0     242.0     23.2     25.4     30.0  11.5200  4.0200
1     290.0     24.0     26.3     31.2  12.4800  4.3056
2     340.0     23.9     26.5     31.1  12.3778  4.6961
3     363.0     26.3     29.0     33.5  12.7300  4.4555
4     430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154    12.2     11.5     12.2     13.4   2.0904  1.3936
155    13.4     11.7     12.4     13.5   2.4300  1.2690
156    12.2     12.1     13.0     13.8   2.2770  1.2558
157    19.7     13.2     14.3     15.2   2.8728  2.0672
158    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns] 0      Bream
1      Bream
2      Bream
3      Bream
4      Bream
       ...  
154    Smelt
155    Smelt
156    Smelt
157    Smelt
158    Smelt
Name: Species, Length: 159, dtype: object


Splitting Data in Testing and Training


In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


Preprocessing the data

In [72]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Training the model

In [73]:
from sklearn.svm import SVC
model = SVC (kernel = 'linear', C = 1) 
model.fit(X_train, y_train)

SVC(C=1, kernel='linear')

In [74]:
y_pred = model.predict(X_test)

Metrics

In [75]:
from sklearn.metrics import accuracy_score
accuracy_score = model.score(X_train, y_train)

In [76]:
print("Training Accuracy is",accuracy_score*100)

Training Accuracy is 82.67716535433071


Confusion Matrix

In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 9  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  7  0  0  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  1  0  0  0  0]]


0.75

Testing 

In [78]:
accuracy = model.score(X_test, y_test)
print("Testing accuracy is:",accuracy)

Testing accuracy is: 0.75
