# Name: Rushikesh Jyoti
# Divsion: A
# Roll no: 27
# SRN: 201901139

# Problem Statement

Write a program to implement single perceptron model Using ANN.  Use suitbale datatset.

# Single Perceptron Model

<!-- <img src=./perceptron_image.png width=720> -->

<img src=https://images.deepai.org/glossary-terms/perceptron-6168423.jpg width=720>

In [8]:
import numpy as np 

The given weights and biases are taken from notes on **16/11/2022**

In [9]:
fruits = np.array([
    [121, 16.8], # Fruit 1
    [114, 15.2], # Fruit 1
    [210, 9.4],  # Fruit 2
    [196, 8.1],  # Fruit 2
])

fruits.shape

(4, 2)

In [10]:
correct_weights = np.array(
    # Bias   w1     w2
    # |      |      |
    # v      v      v
    [50,    -30,  300],
    dtype=np.float64
)

# Make changes here, change the input fruit's weight and length
#               |
#               v
inputs = fruits[3]
# inputs = [140, 17.9]   # Unknown Fruit

inputs = np.pad(inputs, (1, 0), mode='constant', constant_values = 1) # Padding input with 1 at the start of array

print(correct_weights.shape)
print(inputs.shape)
print(inputs)

(3,)
(3,)
[  1.  196.    8.1]


Weighted Input

In [11]:
wi = correct_weights.dot(inputs)
wi 

-3400.0

Activation Function

In [12]:
print("Sign", np.sign(wi))
print("Tanh", np.tanh(wi))
# print("Sigmoid", 1 / (1 + np.exp(-wi))) 
# print("ReLu", wi if wi >= 0 else 0) 

Sign -1.0
Tanh -1.0


---

In [13]:
# These weights are based on trial and error
weights = np.array(
    [-1230, 50, 300],
    dtype=np.float64
)

In [14]:
fruit_index = 2
inputs = fruits[fruit_index]
inputs = np.pad(inputs, (1, 0), constant_values=1)

inputs

array([  1. , 210. ,   9.4])

In [15]:
actual = 1 if fruit_index < 2 else -1
actual

-1

Rerun from the bottom cell to update weights and biases

In [16]:
ws = weights.dot(inputs)
ws

12090.0

In [17]:
def activation(value) -> int: 
    return int(np.sign(value))

predicted = activation(ws)
predicted

1

In [18]:
learning_rate = 0.1

if actual != predicted:
    print(f"Actual is {actual}, predicted is {predicted}")
    print(f"Changed weights from {weights} to ", end='')
    weights = weights + learning_rate * (actual - predicted) * inputs
    print(f"{weights}", end='')
else:
    print("Prediction is right")

Actual is -1, predicted is 1
Changed weights from [-1230.    50.   300.] to [-1230.2      8.     298.12]

In [19]:
weights

array([-1230.2 ,     8.  ,   298.12])